'use client';
import { useEffect,useState } from 'react';

type Name='wildberries'|'ozon';

export default function Page(){
 const [cfg,setCfg]=useState({wildberries:false,ozon:false});
 const [busy,setBusy]=useState('');
 const [msg,setMsg]=useState<Record<string,string>>({});
 const load=async()=>{const r=await fetch('/api/admin/integrations/status',{cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setCfg(j.configured||cfg);else setMsg({global:r.status===401?'Сначала войдите в админку':(j.error||'Ошибка')})};
 useEffect(()=>{load()},[]);
 const run=async(name:Name,action:'test'|'sync')=>{const k=`${name}-${action}`;setBusy(k);setMsg(m=>({...m,[name]:action==='test'?'Проверяем…':'Синхронизируем…'}));try{const r=await fetch(`/api/admin/integrations/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({marketplace:name})});const j=await r.json().catch(()=>({}));setMsg(m=>({...m,[name]:r.ok?(action==='test'?'✓ Подключение работает':`✓ Синхронизировано: ${j.synced||0}`):`Ошибка: ${j.error||r.status}`}));}catch{setMsg(m=>({...m,[name]:'Ошибка сети'}));}finally{setBusy('')}};
 const card=(name:Name,title:string,setup:string)=>{const ok=cfg[name];return <section className="admin-card editor"><div className="editor-head"><div><h2>{title}</h2><span>Заказы + отзывы и вопросы</span></div><b>{ok?'● Ключи найдены':'○ Ключи не найдены'}</b></div><p>{setup}</p><div className="editor-actions"><button className="edit-btn" disabled={!!busy} onClick={()=>run(name,'test')}>{busy===`${name}-test`?'Проверка…':'Проверить'}</button><button className="save-btn" disabled={!!busy} onClick={()=>run(name,'sync')}>{busy===`${name}-sync`?'Синхронизация…':'Синхронизировать заказы'}</button></div>{!ok&&<p style={{color:'#a15b18'}}>Кнопки теперь активны: при нажатии сервер покажет, какой именно ключ отсутствует.</p>}{msg[name]&&<p>{msg[name]}</p>}</section>};
 return <main className="admin-shell"><div className="admin-top"><div><h1>Интеграции</h1><p>Wildberries и Ozon Seller API</p></div><button className="edit-btn" onClick={load}>Обновить статус</button></div>{msg.global&&<section className="admin-card editor"><p>{msg.global} <a href="/admin">Войти</a></p></section>}{card('wildberries','Wildberries','Для заказов нужен WB_API_TOKEN с доступом Marketplace. Для отзывов и вопросов можно использовать тот же токен, если у него есть категория «Вопросы и отзывы», либо отдельный WB_FEEDBACK_TOKEN.')}{card('ozon','Ozon','Нужны OZON_CLIENT_ID и OZON_API_KEY. Доступ к отзывам/вопросам у Ozon может зависеть от тарифа и прав API-ключа.')}<section className="admin-card editor"><h2>Работа с покупателями</h2><p><a href="/admin/communications">Открыть отзывы и вопросы →</a></p><p>Там можно загрузить необработанные обращения и отправить ответ прямо в Wildberries или Ozon через API.</p></section><section className="admin-card editor"><h2>Общий список заказов</h2><p>После синхронизации откройте <a href="/admin/orders">Заказы</a>.</p></section></main>
}
