'use client';
import { useEffect,useState } from 'react';

type Name='wildberries'|'ozon';
type Config={wildberries:boolean;ozon:boolean;avito:boolean;vk?:boolean;yandex?:boolean};

export default function Page(){
 const [cfg,setCfg]=useState<Config>({wildberries:false,ozon:false,avito:false,vk:false,yandex:false});
 const [busy,setBusy]=useState('');
 const [msg,setMsg]=useState<Record<string,string>>({});
 const load=async()=>{const r=await fetch('/api/admin/integrations/status',{cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setCfg(j.configured||cfg);else setMsg({global:r.status===401?'Сначала войдите в админку':(j.error||'Ошибка')})};
 useEffect(()=>{load()},[]);
 const run=async(name:Name,action:'test'|'sync')=>{const k=`${name}-${action}`;setBusy(k);setMsg(m=>({...m,[name]:action==='test'?'Проверяем…':'Синхронизируем…'}));try{const r=await fetch(`/api/admin/integrations/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({marketplace:name})});const j=await r.json().catch(()=>({}));setMsg(m=>({...m,[name]:r.ok?(action==='test'?'✓ Подключение работает':`✓ Синхронизировано: ${j.synced||0}`):`Ошибка: ${j.error||r.status}`}));}catch{setMsg(m=>({...m,[name]:'Ошибка сети'}));}finally{setBusy('')}};
 const runYandex=async(action:'test'|'sync')=>{const key=`yandex-${action}`;setBusy(key);setMsg(m=>({...m,yandex_market:action==='test'?'Проверяем…':'Синхронизируем…'}));try{const r=await fetch(`/api/admin/integrations/yandex-${action}`,{method:'POST'});const j=await r.json().catch(()=>({}));setMsg(m=>({...m,yandex_market:r.ok?(action==='test'?'✓ FBS подключён':`✓ Синхронизировано: ${j.synced||0}`):`Ошибка: ${j.error||r.status}`}));}catch{setMsg(m=>({...m,yandex_market:'Ошибка сети'}));}finally{setBusy('')}};
 const testAvito=async()=>{setBusy('avito-test');setMsg(m=>({...m,avito:'Проверяем…'}));try{const r=await fetch('/api/admin/integrations/avito-test',{method:'POST'});const j=await r.json().catch(()=>({}));setMsg(m=>({...m,avito:r.ok?'✓ Подключение работает':`Ошибка: ${j.error||r.status}`}));}catch{setMsg(m=>({...m,avito:'Ошибка сети'}));}finally{setBusy('')}};
 const runVk=async(action:'test'|'sync')=>{const key=`vk-${action}`;setBusy(key);setMsg(m=>({...m,vk:action==='test'?'Проверяем VK…':'Выгружаем каталог Ozon в VK и забираем заказы…'}));try{const r=await fetch(`/api/admin/integrations/vk-${action}`,{method:'POST'});const j=await r.json().catch(()=>({}));const text=r.ok?(action==='test'?'✓ VK подключён':`✓ VK: создано ${j.catalog?.created||0}, обновлено ${j.catalog?.updated||0}, ошибок ${j.catalog?.failed||0}; заказов ${j.orders?.synced||0}`):`Ошибка: ${j.error||r.status}`;setMsg(m=>({...m,vk:text}));}catch{setMsg(m=>({...m,vk:'Ошибка сети'}));}finally{setBusy('')}};
 const card=(name:Name,title:string,setup:string)=>{const ok=cfg[name];return <section className="admin-card editor"><div className="editor-head"><div><h2>{title}</h2><span>Заказы + отзывы и вопросы</span></div><b>{ok?'● Ключи найдены':'○ Ключи не найдены'}</b></div><p>{setup}</p><div className="editor-actions"><button className="edit-btn" disabled={!!busy} onClick={()=>run(name,'test')}>{busy===`${name}-test`?'Проверка…':'Проверить'}</button><button className="save-btn" disabled={!!busy} onClick={()=>run(name,'sync')}>{busy===`${name}-sync`?'Синхронизация…':'Синхронизировать заказы'}</button></div>{msg[name]&&<p>{msg[name]}</p>}</section>};
 return <main className="admin-shell">
  <div className="admin-top"><div><h1>Интеграции</h1><p>Маркетплейсы, соцсети и единый список заказов</p></div><button className="edit-btn" onClick={load}>Обновить статус</button></div>
  {msg.global&&<section className="admin-card editor"><p>{msg.global} <a href="/admin">Войти</a></p></section>}
  {card('wildberries','Wildberries','Для заказов нужен WB_API_TOKEN с доступом Marketplace. Для отзывов и вопросов можно использовать WB_FEEDBACK_TOKEN.')}
  {card('ozon','Ozon','Нужны OZON_CLIENT_ID и OZON_API_KEY.')}
  <section className="admin-card editor"><div className="editor-head"><div><h2>VK Магазин</h2><span>Каталог Ozon → VK + заказы VK → TechRoom</span></div><b>{cfg.vk?'● Подключён':'○ Нужны ключи'}</b></div><p>Интеграция создаёт и обновляет товары сообщества VK из каталога Ozon: название, описание, артикул, цену, категорию и главное фото. Заказы из VK попадают в общий раздел заказов TechRoom.</p><p>Нужны <code>VK_GROUP_ID</code> и <code>VK_ACCESS_TOKEN</code> с правами управления товарами сообщества.</p><div className="editor-actions"><button className="edit-btn" disabled={!!busy} onClick={()=>runVk('test')}>{busy==='vk-test'?'Проверка…':'Проверить VK'}</button><button className="save-btn" disabled={!!busy} onClick={()=>runVk('sync')}>{busy==='vk-sync'?'Синхронизация…':'Выгрузить Ozon → VK'}</button></div>{msg.vk&&<p>{msg.vk}</p>}</section>
  <section className="admin-card editor"><div className="editor-head"><div><h2>Avito</h2><span>Цены объявлений через API</span></div><b>{cfg.avito?'● Ключи найдены':'○ Нужны ключи'}</b></div><p>Нужны AVITO_CLIENT_ID и AVITO_CLIENT_SECRET. SKU автоматически сопоставляются с ID объявлений через Autoload.</p><div className="editor-actions"><button className="edit-btn" disabled={!!busy} onClick={testAvito}>{busy==='avito-test'?'Проверка…':'Проверить'}</button><a className="save-btn" href="/admin/prices" style={{textDecoration:'none'}}>Лист цен</a></div>{msg.avito&&<p>{msg.avito}</p>}</section>
  <section className="admin-card editor"><div className="editor-head"><div><h2>Яндекс Маркет FBS</h2><span>Заказы, цены и остатки магазина RYBS 2</span></div><b>{cfg.yandex?'● Подключён':'○ Нужны ключи'}</b></div><p>Используются <code>YANDEX_MARKET_API_KEY</code>, <code>YANDEX_MARKET_BUSINESS_ID</code> и <code>YANDEX_MARKET_CAMPAIGN_ID</code>. Интеграция принимает только FBS и не изменяет магазин FBY.</p><div className="editor-actions"><button className="edit-btn" disabled={!!busy} onClick={()=>runYandex('test')}>{busy==='yandex-test'?'Проверка…':'Проверить'}</button><button className="save-btn" disabled={!!busy} onClick={()=>runYandex('sync')}>{busy==='yandex-sync'?'Синхронизация…':'Синхронизировать заказы'}</button></div>{msg.yandex_market&&<p>{msg.yandex_market}</p>}</section>
  <section className="admin-card editor"><h2>Avito, Мегамаркет, AliExpress и другие</h2><p>Для этих площадок добавлен универсальный импорт заказов в TechRoom.</p><p>Для внешней автоматизации используется серверный маршрут <code>/api/admin/orders/import</code>.</p></section>
  <section className="admin-card editor"><h2>Работа с покупателями</h2><p><a href="/admin/communications">Открыть отзывы и вопросы →</a></p></section>
  <section className="admin-card editor"><h2>Общий список заказов</h2><p><a href="/admin/orders">Открыть все заказы →</a></p></section>
 </main>
}
