'use client';
import { useEffect,useState } from 'react';

type Name='wildberries'|'ozon';

export default function Page(){
 const [cfg,setCfg]=useState({wildberries:false,ozon:false,avito:false});
 const [busy,setBusy]=useState('');
 const [msg,setMsg]=useState<Record<string,string>>({});
 const load=async()=>{const r=await fetch('/api/admin/integrations/status',{cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setCfg(j.configured||cfg);else setMsg({global:r.status===401?'Сначала войдите в админку':(j.error||'Ошибка')})};
 useEffect(()=>{load()},[]);
 const run=async(name:Name,action:'test'|'sync')=>{const k=`${name}-${action}`;setBusy(k);setMsg(m=>({...m,[name]:action==='test'?'Проверяем…':'Синхронизируем…'}));try{const r=await fetch(`/api/admin/integrations/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({marketplace:name})});const j=await r.json().catch(()=>({}));setMsg(m=>({...m,[name]:r.ok?(action==='test'?'✓ Подключение работает':`✓ Синхронизировано: ${j.synced||0}`):`Ошибка: ${j.error||r.status}`}));}catch{setMsg(m=>({...m,[name]:'Ошибка сети'}));}finally{setBusy('')}};
 const runYandex=async(action:'test'|'sync')=>{const key=`yandex-${action}`;setBusy(key);setMsg(m=>({...m,yandex_market:action==='test'?'Проверяем…':'Синхронизируем…'}));try{const r=await fetch(`/api/admin/integrations/yandex-${action}`,{method:'POST'});const j=await r.json().catch(()=>({}));setMsg(m=>({...m,yandex_market:r.ok?(action==='test'?'✓ Подключение работает':`✓ Синхронизировано: ${j.synced||0}`):`Ошибка: ${j.error||r.status}`}));}catch{setMsg(m=>({...m,yandex_market:'Ошибка сети'}));}finally{setBusy('')}};
 const testAvito=async()=>{setBusy('avito-test');setMsg(m=>({...m,avito:'Проверяем…'}));try{const r=await fetch('/api/admin/integrations/avito-test',{method:'POST'});const j=await r.json().catch(()=>({}));setMsg(m=>({...m,avito:r.ok?'✓ Подключение работает':`Ошибка: ${j.error||r.status}`}));}catch{setMsg(m=>({...m,avito:'Ошибка сети'}));}finally{setBusy('')}};
 const card=(name:Name,title:string,setup:string)=>{const ok=cfg[name];return <section className="admin-card editor"><div className="editor-head"><div><h2>{title}</h2><span>Заказы + отзывы и вопросы</span></div><b>{ok?'● Ключи найдены':'○ Ключи не найдены'}</b></div><p>{setup}</p><div className="editor-actions"><button className="edit-btn" disabled={!!busy} onClick={()=>run(name,'test')}>{busy===`${name}-test`?'Проверка…':'Проверить'}</button><button className="save-btn" disabled={!!busy} onClick={()=>run(name,'sync')}>{busy===`${name}-sync`?'Синхронизация…':'Синхронизировать заказы'}</button></div>{msg[name]&&<p>{msg[name]}</p>}</section>};
 return <main className="admin-shell"><div className="admin-top"><div><h1>Интеграции</h1><p>Маркетплейсы и единый список заказов</p></div><button className="edit-btn" onClick={load}>Обновить статус</button></div>{msg.global&&<section className="admin-card editor"><p>{msg.global} <a href="/admin">Войти</a></p></section>}{card('wildberries','Wildberries','Для заказов нужен WB_API_TOKEN с доступом Marketplace. Для отзывов и вопросов можно использовать WB_FEEDBACK_TOKEN.')}{card('ozon','Ozon','Нужны OZON_CLIENT_ID и OZON_API_KEY.')}<section className="admin-card editor"><div className="editor-head"><div><h2>Avito</h2><span>Цены объявлений через API</span></div><b>{cfg.avito?'● Ключи найдены':'○ Ключи не найдены'}</b></div><p>Нужны AVITO_CLIENT_ID и AVITO_CLIENT_SECRET. SKU автоматически сопоставляются с ID объявлений через Autoload; при необходимости Avito ID можно указать вручную в «Листе цен».</p><div className="editor-actions"><button className="edit-btn" disabled={!!busy} onClick={testAvito}>{busy==='avito-test'?'Проверка…':'Проверить'}</button><a className="save-btn" href="/admin/prices" style={{textDecoration:'none'}}>Лист цен</a></div>{msg.avito&&<p>{msg.avito}</p>}</section><section className="admin-card editor"><div className="editor-head"><div><h2>Яндекс Маркет</h2><span>Заказы через Seller API</span></div></div><p>Добавьте YANDEX_MARKET_API_KEY и YANDEX_MARKET_BUSINESS_ID в Render. Токену нужен доступ к просмотру/обработке заказов.</p><div className="editor-actions"><button className="edit-btn" disabled={!!busy} onClick={()=>runYandex('test')}>{busy==='yandex-test'?'Проверка…':'Проверить'}</button><button className="save-btn" disabled={!!busy} onClick={()=>runYandex('sync')}>{busy==='yandex-sync'?'Синхронизация…':'Синхронизировать заказы'}</button></div>{msg.yandex_market&&<p>{msg.yandex_market}</p>}</section><section className="admin-card editor"><h2>Avito, Мегамаркет, AliExpress и другие</h2><p>Для этих площадок добавлен универсальный импорт заказов в TechRoom. Источники отображаются в общем разделе заказов как Avito, Мегамаркет, AliExpress или «Другой маркетплейс».</p><p>Для внешней автоматизации используется серверный маршрут <code>/api/admin/orders/import</code>. Для безопасного внешнего импорта задайте в Render переменную <code>MARKETPLACE_IMPORT_SECRET</code>.</p></section><section className="admin-card editor"><h2>Работа с покупателями</h2><p><a href="/admin/communications">Открыть отзывы и вопросы →</a></p></section><section className="admin-card editor"><h2>Общий список заказов</h2><p><a href="/admin/orders">Открыть все заказы →</a></p></section></main>
}
