import { NextResponse } from "next/server";
import { isAdminSession } from "../../../../../lib/security";import { ensurePriceSheetSchema } from "../../../../../lib/price-sheet";import { getPool } from "../../../../../lib/db";
export const runtime="nodejs";export const dynamic="force-dynamic";
const round=(v:number)=>Math.round(v*100)/100;
export async function GET(request:Request){if(!isAdminSession(request))return NextResponse.json({ok:false,error:"Требуется вход администратора"},{status:401});const token=process.env.WB_API_TOKEN?.trim();if(!token)return NextResponse.json({ok:false,error:"WB_API_TOKEN_NOT_CONFIGURED"},{status:503});const u=new URL(request.url),now=new Date(),from=u.searchParams.get("from")||new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString(),to=u.searchParams.get("to")||now.toISOString();
 try{const r=await fetch("https://statistics-api.wildberries.ru/api/v5/supplier/reportDetailByPeriod?dateFrom="+encodeURIComponent(from)+"&dateTo="+encodeURIComponent(to)+"&limit=100000",{headers:{Authorization:token},cache:"no-store"});if(!r.ok)throw new Error("WB_API_"+r.status+": "+(await r.text()).slice(0,300));const rows:any[]=await r.json();await ensurePriceSheetSchema();const q=await getPool().query("SELECT sku,title,cost_price FROM price_sheet");const costs:Record<string,any>={};for(const x of q.rows)costs[String(x.sku)]={title:x.title,cost:Number(x.cost_price)||0};const map:Record<string,any>={};let sales=0,fees=0,logistics=0,storage=0,penalties=0,payout=0;
 for(const x of rows){const sku=String(x.supplierArticle??x.nmId??"Без SKU"),sale=Number(x.retail_amount??x.retail_price_withdisc_rub??0)||0,commission=Number(x.ppvz_sales_commission??0)||0,log=Number(x.delivery_rub??0)||0,store=Number(x.storage_fee??0)||0,pen=Number(x.penalty??0)||0,pay=Number(x.ppvz_for_pay??0)||0;sales+=sale;fees+=commission;logistics+=log;storage+=store;penalties+=pen;payout+=pay;map[sku]??={sku,title:costs[sku]?.title??sku,qty:0,sales:0,expenses:0,payout:0};map[sku].qty+=Number(x.quantity??1)||1;map[sku].sales+=sale;map[sku].expenses+=commission+log+store+pen;map[sku].payout+=pay;}
 const skuEconomics=Object.values(map).map((x:any)=>{const cost=(costs[x.sku]?.cost||0)*x.qty,profit=x.payout-cost;return{...x,sales:round(x.sales),expenses:round(x.expenses),payout:round(x.payout),costPrice:costs[x.sku]?.cost||0,profit:round(profit),margin:x.sales?round(profit/x.sales*100):0}}).sort((a:any,b:any)=>b.sales-a.sales);
 const rec:any[]=[];const burden=sales?Math.abs(fees+logistics+storage+penalties)/sales*100:0;if(burden>30)rec.push({level:"high",title:"Высокие расходы Wildberries",text:"Комиссии, логистика, хранение и штрафы составляют "+round(burden)+"% продаж."});if(penalties)rec.push({level:"high",title:"Есть штрафы",text:"Штрафы за период: "+round(penalties)+" ₽. Проверьте причины в кабинете WB."});for(const x of skuEconomics.filter((x:any)=>x.costPrice>0&&x.profit<0).slice(0,5))rec.push({level:"high",title:"Убыточный SKU "+x.sku,text:"Расчётная прибыль "+x.profit+" ₽ при текущей себестоимости."});
 return NextResponse.json({ok:true,from,to,summary:{sales:round(sales),commission:round(fees),logistics:round(logistics),storage:round(storage),penalties:round(penalties),payout:round(payout),takeRate:round(burden),operations:rows.length,skuEconomics,recommendations:rec}},{headers:{"Cache-Control":"no-store"}})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:"WB_REQUEST_FAILED"},{status:502})}}
