'use client';
import { useEffect, useMemo, useState } from 'react';
import styles from './max.module.css';

declare global { interface Window { WebApp?: any } }
type Product={id:number;category:string;title:string;price:number;oldPrice?:number|null;imageUrl?:string|null;emoji?:string|null;stock:number;description?:string|null;specs?:string|null;sku?:string|null};
type Cart=Record<number,number>; type Tab='catalog'|'cart'|'orders';
const money=(n:number)=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const status:Record<string,string>={new:'Новый',confirmed:'Подтверждён',processing:'В работе',shipped:'Отправлен',completed:'Завершён',cancelled:'Отменён'};

export default function MaxShop(){
 const [initData,setInitData]=useState('');const [products,setProducts]=useState<Product[]>([]);const [cart,setCart]=useState<Cart>({});const [tab,setTab]=useState<Tab>('catalog');const [category,setCategory]=useState('Все');const [query,setQuery]=useState('');const [selected,setSelected]=useState<Product|null>(null);const [orders,setOrders]=useState<any[]>([]);const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const [form,setForm]=useState({customerName:'',phone:'',deliveryMethod:'courier',address:'',paymentMethod:'qr',comment:''});
 useEffect(()=>{const tg=window.WebApp;const data=tg?.initData||'';setInitData(data);const start=new URLSearchParams(location.search).get('tab');if(start==='orders')setTab('orders');try{setCart(JSON.parse(localStorage.getItem('techroom_max_cart')||'{}'))}catch{};if(tg?.initDataUnsafe?.user)setForm(f=>({...f,customerName:[tg.initDataUnsafe.user.first_name,tg.initDataUnsafe.user.last_name].filter(Boolean).join(' ')}))},[]);
 useEffect(()=>{if(!initData)return;fetch('/api/max/products',{headers:{'X-Max-Init-Data':initData}}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);return j}).then(setProducts).catch(e=>setNotice(e.message||'Не удалось загрузить каталог.'))},[initData]);
 useEffect(()=>{localStorage.setItem('techroom_max_cart',JSON.stringify(cart))},[cart]);
 useEffect(()=>{if(tab==='orders'&&initData)fetch('/api/max/orders',{headers:{'X-Max-Init-Data':initData},cache:'no-store'}).then(r=>r.json()).then(j=>Array.isArray(j)?setOrders(j):setNotice(j.error))},[tab,initData]);
 const categories=['Все',...Array.from(new Set(products.map(p=>p.category)))];const visible=useMemo(()=>products.filter(p=>(category==='Все'||p.category===category)&&(`${p.title} ${p.sku||''}`.toLowerCase().includes(query.toLowerCase()))),[products,category,query]);
 const lines=Object.entries(cart).map(([id,quantity])=>({product:products.find(p=>p.id===Number(id)),quantity})).filter(x=>x.product) as {product:Product;quantity:number}[];const count=lines.reduce((s,x)=>s+x.quantity,0),total=lines.reduce((s,x)=>s+x.quantity*x.product.price,0);
 const change=(id:number,q:number)=>setCart(c=>{const n={...c};if(q<1)delete n[id];else n[id]=q;return n});
 const checkout=async()=>{setNotice('');if(!form.customerName||!form.phone||(form.deliveryMethod==='courier'&&!form.address)){setNotice('Заполните имя, телефон и адрес доставки.');return}setBusy(true);try{const r=await fetch('/api/max/orders',{method:'POST',headers:{'Content-Type':'application/json','X-Max-Init-Data':initData},body:JSON.stringify({...form,items:lines.map(x=>({productId:x.product.id,quantity:x.quantity}))})});const j=await r.json();if(!r.ok)throw new Error(j.error);setCart({});setNotice(`Заказ ${j.orderNumber} создан`);setTab('orders');window.WebApp?.HapticFeedback?.notificationOccurred('success')}catch(e:any){setNotice(e.message||'Ошибка оформления')}finally{setBusy(false)}};
 const manager=process.env.NEXT_PUBLIC_MAX_MANAGER_URL||'https://max.ru/';
 if(!initData)return <main className={styles.shell}><div className={styles.center}><div className={styles.logo}>TR</div><h1>TechRoom</h1><p>Для безопасного входа откройте магазин кнопкой в боте MAX.</p></div></main>;
 return <main className={styles.shell}><header><div><b>Tech<span>Room</span></b><small>магазин в MAX</small></div><button onClick={()=>window.WebApp?.openMaxLink(manager)}>Менеджер</button></header>
  {notice&&<div className={styles.notice} onClick={()=>setNotice('')}>{notice}</div>}
  {tab==='catalog'&&<><div className={styles.search}><input placeholder="Поиск по товарам и артикулу" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className={styles.chips}>{categories.map(c=><button className={category===c?styles.active:''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><section className={styles.grid}>{visible.map(p=><article className={styles.card} key={p.id}><button className={styles.visual} onClick={()=>setSelected(p)}>{p.imageUrl?<img src={p.imageUrl} alt=""/>:<span>{p.emoji||'📦'}</span>}</button><small>{p.category}</small><h2 onClick={()=>setSelected(p)}>{p.title}</h2><div className={styles.stock}>{p.stock>0?`В наличии · ${p.stock} шт.`:'Нет в наличии'}</div><div className={styles.price}><b>{money(p.price)}</b>{p.oldPrice&&<del>{money(p.oldPrice)}</del>}</div><button className={styles.add} disabled={!p.stock} onClick={()=>change(p.id,Math.min(p.stock,(cart[p.id]||0)+1))}>{cart[p.id]?`В корзине: ${cart[p.id]}`:'В корзину'}</button></article>)}</section>{!visible.length&&<div className={styles.empty}>Товары не найдены</div>}</>}
  {tab==='cart'&&<section className={styles.panel}><h1>Корзина</h1>{!lines.length?<div className={styles.empty}>Корзина пуста</div>:<><div className={styles.lines}>{lines.map(({product:p,quantity:q})=><div className={styles.line} key={p.id}><div className={styles.thumb}>{p.imageUrl?<img src={p.imageUrl} alt=""/>:p.emoji||'📦'}</div><div><b>{p.title}</b><small>{money(p.price)}</small><div className={styles.counter}><button onClick={()=>change(p.id,q-1)}>−</button><span>{q}</span><button disabled={q>=p.stock} onClick={()=>change(p.id,q+1)}>+</button></div></div><strong>{money(p.price*q)}</strong></div>)}</div><div className={styles.total}><span>Итого</span><b>{money(total)}</b></div><div className={styles.form}><input placeholder="Имя *" value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/><input placeholder="Телефон *" inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><select value={form.deliveryMethod} onChange={e=>setForm({...form,deliveryMethod:e.target.value})}><option value="courier">Доставка</option><option value="pickup">Самовывоз</option></select>{form.deliveryMethod==='courier'&&<input placeholder="Адрес доставки *" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/>}<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}><option value="qr">QR / СБП</option><option value="cash">При получении</option></select><textarea placeholder="Комментарий к заказу" value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})}/><button className={styles.checkout} disabled={busy} onClick={checkout}>{busy?'Оформляем…':`Оформить · ${money(total)}`}</button><small className={styles.hint}>Оплата через MAX будет доступна после подключения провайдера. Сейчас работают способы TechRoom.</small></div></>}</section>}
  {tab==='orders'&&<section className={styles.panel}><h1>Мои заказы</h1>{orders.length?orders.map(o=><div className={styles.order} key={o.order_number}><div><b>{o.order_number}</b><small>{new Date(o.created_at).toLocaleDateString('ru-RU')}</small></div><div><span>{status[o.status]||o.status}</span><strong>{money(o.total_amount)}</strong></div></div>):<div className={styles.empty}>Заказов пока нет</div>}</section>}
  {selected&&<div className={styles.overlay} onClick={()=>setSelected(null)}><div className={styles.modal} onClick={e=>e.stopPropagation()}><button className={styles.close} onClick={()=>setSelected(null)}>×</button><div className={styles.modalImage}>{selected.imageUrl?<img src={selected.imageUrl} alt=""/>:selected.emoji||'📦'}</div><small>{selected.category} · {selected.sku||'TechRoom'}</small><h1>{selected.title}</h1><p>{selected.description||'Подробности уточняйте у менеджера.'}</p>{selected.specs&&<pre>{selected.specs}</pre>}<b className={styles.modalPrice}>{money(selected.price)}</b><button className={styles.checkout} disabled={!selected.stock} onClick={()=>{change(selected.id,Math.min(selected.stock,(cart[selected.id]||0)+1));setSelected(null)}}>Добавить в корзину</button></div></div>}
  <nav><button className={tab==='catalog'?styles.current:''} onClick={()=>setTab('catalog')}>⌂<span>Каталог</span></button><button className={tab==='cart'?styles.current:''} onClick={()=>setTab('cart')}>🛒<span>Корзина{count?` · ${count}`:''}</span></button><button className={tab==='orders'?styles.current:''} onClick={()=>setTab('orders')}>▤<span>Заказы</span></button></nav>
 </main>
}
